src/Entity/Measurement.php
<?php

namespace App\Entity;

use App\Repository\MeasurementRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MeasurementRepository::class)]
class Measurement
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'measurements')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Location $location = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 3, scale: 0)]
    private ?string $celsius = null;

    #[ORM\Column(length: 20)]
    private ?string $weather = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 3, scale: 2)]
    private ?string $wind_speed = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 3, scale: 2)]
    private ?string $pressure = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 3, scale: 2)]
    private ?string $humidity = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLocation(): ?Location
    {
        return $this->location;
    }

    public function setLocation(?Location $location): static
    {
        $this->location = $location;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): static
    {
        $this->date = $date;

        return $this;
    }

    public function getCelsius(): ?string
    {
        return $this->celsius;
    }

    public function setCelsius(string $celsius): static
    {
        $this->celsius = $celsius;

        return $this;
    }

    public function getWeather(): ?string
    {
        return $this->weather;
    }

    public function setWeather(string $weather): static
    {
        $this->weather = $weather;

        return $this;
    }

    public function getWindSpeed(): ?string
    {
        return $this->wind_speed;
    }

    public function setWindSpeed(string $wind_speed): static
    {
        $this->wind_speed = $wind_speed;

        return $this;
    }

    public function getPressure(): ?string
    {
        return $this->pressure;
    }

    public function setPressure(string $pressure): static
    {
        $this->pressure = $pressure;

        return $this;
    }

    public function getHumidity(): ?string
    {
        return $this->humidity;
    }

    public function setHumidity(string $humidity): static
    {
        $this->humidity = $humidity;

        return $this;
    }
    public function getFahrenheit(): ?string
    {
        $fahrenheit = $this->getCelsius() * 9 / 5 + 32;
        return "$fahrenheit";
    }
}

src/Form/MeasurementType.php
<?php

namespace App\Form;

use App\Entity\Location;
use App\Entity\Measurement;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MeasurementType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('date', DateType::class, [
                'widget' => 'single_text',
                'html5' => true,
            ])
            ->add('celsius', NumberType::class, [
                'attr' => [
                    'min' => -20,
                    'max' => 40,
                ],
                'html5' => true,
            ])
            ->add('weather', TextType::class, [
                'attr' => [
                    'placeholder' => 'Describe weather conditions',
                ],
            ])
            ->add('wind_speed', NumberType::class, [
                'attr' => [
                    'min' => 0,
                    'step' => 0.1,
                ],
                'html5' => true,
            ])
            ->add('pressure', NumberType::class, [
                'attr' => [
                    'min' => 900,
                    'max' => 1100,
                ],
                'html5' => true,
            ])
            ->add('humidity', NumberType::class, [
                'attr' => [
                    'min' => 0,
                    'max' => 100,
                ],
                'html5' => true,
            ])
//            ->add('location', EntityType::class, [
//                'class' => Location::class,
//                'choice_label' => 'id',
//            ])
            ->add('location', EntityType::class, [
                'class' => 'App\Entity\Location',
                'choice_label' => 'city',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Measurement::class,
        ]);
    }
}

src/Controller/MeasurementController.php
<?php

namespace App\Controller;

use App\Entity\Measurement;
use App\Form\MeasurementType;
use App\Repository\MeasurementRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[Route('/measurement')]
class MeasurementController extends AbstractController
{
    #[Route('/', name: 'app_measurement_index', methods: ['GET'])]
    #[IsGranted('ROLE_MEASUREMENT_INDEX')]
    public function index(MeasurementRepository $measurementRepository): Response
    {
        return $this->render('measurement/index.html.twig', [
            'measurements' => $measurementRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_measurement_new', methods: ['GET', 'POST'])]
    #[IsGranted('ROLE_MEASUREMENT_NEW')]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $measurement = new Measurement();
        $form = $this->createForm(MeasurementType::class, $measurement, [
            'validation_groups' => 'create',
        ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($measurement);
            $entityManager->flush();

            return $this->redirectToRoute('app_measurement_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('measurement/new.html.twig', [
            'measurement' => $measurement,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_measurement_show', methods: ['GET'])]
    #[IsGranted('ROLE_MEASUREMENT_SHOW')]
    public function show(Measurement $measurement): Response
    {
        return $this->render('measurement/show.html.twig', [
            'measurement' => $measurement,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_measurement_edit', methods: ['GET', 'POST'])]
    #[IsGranted('ROLE_MEASUREMENT_EDIT')]
    public function edit(Request $request, Measurement $measurement, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(MeasurementType::class, $measurement, [
            'validation_groups' => 'edit',
        ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_measurement_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('measurement/edit.html.twig', [
            'measurement' => $measurement,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_measurement_delete', methods: ['POST'])]
    #[IsGranted('ROLE_MEASUREMENT_DELETE')]
    public function delete(Request $request, Measurement $measurement, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$measurement->getId(), $request->request->get('_token'))) {
            $entityManager->remove($measurement);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_measurement_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/measurement/_delete_form.html.twig
<form method="post" action="{{ path('app_measurement_delete', {'id': measurement.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ measurement.id) }}">
    <button class="btn">Delete</button>
</form>

templates/measurement/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/measurement/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Measurement{% endblock %}

{% block body %}
    <h1>Edit Measurement</h1>

    {{ include('measurement/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_measurement_index') }}">back to list</a>

    {{ include('measurement/_delete_form.html.twig') }}
{% endblock %}

templates/measurement/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Measurement index{% endblock %}

{% block body %}
    <h1>Measurement index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Date</th>
                <th>Celsius</th>
                <th>Weather</th>
                <th>Wind_speed</th>
                <th>Pressure</th>
                <th>Humidity</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for measurement in measurements %}
            <tr>
                <td>{{ measurement.id }}</td>
                <td>{{ measurement.date ? measurement.date|date('Y-m-d') : '' }}</td>
                <td>{{ measurement.celsius }}</td>
                <td>{{ measurement.weather }}</td>
                <td>{{ measurement.windSpeed }}</td>
                <td>{{ measurement.pressure }}</td>
                <td>{{ measurement.humidity }}</td>
                <td>
                    {% if is_granted('ROLE_MEASUREMENT_SHOW') %}
                        <a href="{{ path('app_measurement_show', {'id': measurement.id}) }}">show</a>
                    {% endif %}
                    {% if is_granted('ROLE_MEASUREMENT_EDIT') %}
                        <a href="{{ path('app_measurement_edit', {'id': measurement.id}) }}">edit</a>
                    {% endif %}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {% if is_granted('ROLE_MEASUREMENT_NEW') %}
        <a href="{{ path('app_measurement_new') }}">Create new</a>
    {% endif %}
{% endblock %}

templates/measurement/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Measurement{% endblock %}

{% block body %}
    <h1>Create new Measurement</h1>

    {{ include('measurement/_form.html.twig') }}

    <a href="{{ path('app_measurement_index') }}">back to list</a>
{% endblock %}

templates/measurement/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Measurement{% endblock %}

{% block body %}
    <h1>Measurement</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ measurement.id }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ measurement.date ? measurement.date|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Celsius</th>
                <td>{{ measurement.celsius }}</td>
            </tr>
            <tr>
                <th>Weather</th>
                <td>{{ measurement.weather }}</td>
            </tr>
            <tr>
                <th>Wind_speed</th>
                <td>{{ measurement.windSpeed }}</td>
            </tr>
            <tr>
                <th>Pressure</th>
                <td>{{ measurement.pressure }}</td>
            </tr>
            <tr>
                <th>Humidity</th>
                <td>{{ measurement.humidity }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_measurement_index') }}">back to list</a>

    <a href="{{ path('app_measurement_edit', {'id': measurement.id}) }}">edit</a>

    {{ include('measurement/_delete_form.html.twig') }}
{% endblock %}